### ISSUE TITLE
Mod errors out with custom album

### ISSUE THREAD

**Issue by confusedcatgirl** [MDMods/CustomAlbums#13]
I got Muse Dash on steam, and this happened all of a sudden, the mod working last night flawlessly.

First and foremost, I am using MelonLoader 0.6.1, CustomAlbums 4.1.1, and the latest version of Muse Dash on Steam, which at the time of writing is version 4.7.0 and Build-ID 15259192.

When I check the logs of MelonLoader, it says the following:

```
Il2CppInterop.Runtime.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
--- BEGIN IL2CPP STACK TRACE ---
System.NullReferenceException: Object reference not set to an instance of an object.
  at Assets.Scripts.PeroTools.Managers.ConfigManager.GetConfigToken (System.String fileName, System.String cmpKey, System.String targetKey, System.Object cmpValue) [0x00000] in <00000000000000000000000000000000>:0 
  at Assets.Scripts.PeroTools.Managers.ConfigManager.GetConfigStringValue (System.String fileName, System.String cmpKey, System.String targetKey, System.Object cmpValue) [0x00000] in <00000000000000000000000000000000>:0 
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at Il2CppAssets.Scripts.PeroTools.Managers.ConfigManager.GetConfigStringValue(String fileName, String cmpKey, String targetKey, Object cmpValue)
   at CustomAlbums.BmsLoader.GetAnimationDuration(String scene, String animation)
   at CustomAlbums.BmsLoader.ProcessBossData(Bms bms)
   at CustomAlbums.BmsLoader.TransmuteData(Bms bms)
   at CustomAlbums.Data.Sheet.GetStage()
   at CustomAlbums.Patches.AssetPatch.<>c.<InitializeHandler>b__8_4(String assetName, IntPtr assetPtr, String _)
   at CustomAlbums.Patches.AssetPatch.LoadFromNamePatch(IntPtr instance, IntPtr assetNamePtr, IntPtr nativeMethodInfo)
```

What seems to be the sudden cause of this? I already redownloaded the mod, tried multiple custom charts, check steam file integrity (It did not fix any files), and even reinstalled MelonLoader.

I would be extremely grateful for help.

**Comment by Hiro420** [comment]
set https://github.com/MDMods/CustomAlbums/blob/c2f9193adafd13ad3a4b0efb517764b4a304af5b/BmsLoader.cs#L656 to try {}  catch {} with default return value

**Comment by confusedcatgirl** [comment]
Alrighty, thanks, I will try to get that going.

**Comment by confusedcatgirl** [comment]
I am not sure what the default value was, so I set it to 1.0f, thanks @Hiro420 !
